#!/usr/bin/env bash
set -euo pipefail

abort() {
  printf "%s\n" "$@"
  exit 1
}

install_policy() {
  policy_dir="$target_dir/usr/share/polkit-1/actions"
  mkdir -p $policy_dir

  # Fill in policy kit file with a list of (the first 10) human users of the system.
  export POLICY_OWNERS
  POLICY_OWNERS="$(cut -d: -f1,3 /etc/passwd | grep -E ':[0-9]{4}$' | cut -d: -f1 | head -n 10 | sed 's/^/unix-user:/' | tr '\n' ' ')"
  eval "cat <<EOF
$(cat $download_dir/com.1password.1Password.policy.tpl)
EOF" > $policy_dir/com.1password.1Password.policy
}

install_desktop() {
  export OP_PATH
  OP_PATH="$(which 1password)"
  desktop_dir=$target_dir/usr/share/applications
  mkdir -p $desktop_dir
  eval "cat <<EOF
$(cat $script_dir/1password.desktop.tpl)
EOF" > $desktop_dir/1password.desktop
}

install_sign_bin() {
  # sign_bin_dir=$target_dir/opt/1Password
  sign_bin_dir=$target_dir/usr/bin
  mkdir -p $sign_bin_dir
  cp $download_dir/op-ssh-sign $sign_bin_dir
}

install_release() {
  version_id="$(grep -E '^VERSION_ID=' /etc/os-release | cut -d= -f2)"
  release_dir=$target_dir/usr/lib/extension-release.d
  mkdir -p $release_dir
  echo "ID=steamos" | sudo tee $release_dir/extension-release.1password
  echo "VERSION_ID=$version_id" | sudo tee -a $release_dir/extension-release.1password
}

current_script_dir() {
    SOURCE=${BASH_SOURCE[0]}
    while [ -L "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
      DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
      SOURCE=$(readlink "$SOURCE")
      [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
    done
    echo $( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
}

register_sysext() {
  mksquashfs $target_dir $raw_path -all-root
  # sudo chown -R root:root $target_dir
  # sudo mv $raw_path /var/lib/extensions/
  sudo ln -s $raw_path /var/lib/extensions/1password.raw
  sudo systemctl enable systemd-sysext
  sudo systemctl start systemd-sysext
  # sudo systemd-sysext refresh
  sudo systemd-sysext merge
  sudo systemd-sysext status
}

verify_env() {
  if ! command -v 1password >/dev/null; then
    abort "Command '1password' not found: 1password must be pre-installed"
  fi
}

download_1password() {
  download_file_path=$download_dir/1password.tar.gz
  curl -s https://downloads.1password.com/linux/tar/stable/x86_64/1password-latest.tar.gz -o $download_file_path
  tar -xf $download_file_path -C $download_dir --wildcards "*op-ssh-sign" --wildcards "*.tpl" --strip-components 1
}

cleanup() {
    rm -rf $download_dir
}

install_extension() {
  mkdir -p $target_dir
  raw_path="$target_dir/1password.raw"

  install_policy
  install_desktop
  install_release
  install_sign_bin
  register_sysext
}

########
# script
verify_env
target_dir="$HOME/.config/1password-sysext"
script_dir=$(current_script_dir)
download_dir=`mktemp -d -t op-download-XXXXXX`
download_1password
trap cleanup exit
source $script_dir/uninstall
install_extension
