#!/usr/bin/env bash
set -euxo pipefail

target_dir="$HOME/.config/1password-sysext"

if [ -f "/var/lib/extensions/1password.raw" ]; then
  sudo rm -f /var/lib/extensions/1password.raw
fi
if [ -d "$target_dir" ]; then
  sudo rm -rf $target_dir
  sudo systemd-sysext refresh
fi
